version: '3.8'

services:
  departamento-usuario:
    image: departamento-usuario:2.0
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_volume:/var/lib/mysql
    restart: always

volumes:
  mysql_volume:
